// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3uPBnA1ffqtQiDkiK-ZGASUmh9tRRguc',
    appId: '1:365750482574:web:206c0b3d06e697e18d7bdf',
    messagingSenderId: '365750482574',
    projectId: 'send-push-e6999',
    authDomain: 'send-push-e6999.firebaseapp.com',
    storageBucket: 'send-push-e6999.firebasestorage.app',
    measurementId: 'G-8KMRVY51N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwCPUrIw-WQ0BOqIheUYPOg4aGth4zGCQ',
    appId: '1:365750482574:android:127666334f77428b8d7bdf',
    messagingSenderId: '365750482574',
    projectId: 'send-push-e6999',
    storageBucket: 'send-push-e6999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdnlcwlQVS4LRW13w2ORQjgeKwS1Pf3fQ',
    appId: '1:365750482574:ios:6a14066ccd18f8cb8d7bdf',
    messagingSenderId: '365750482574',
    projectId: 'send-push-e6999',
    storageBucket: 'send-push-e6999.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdnlcwlQVS4LRW13w2ORQjgeKwS1Pf3fQ',
    appId: '1:365750482574:ios:6a14066ccd18f8cb8d7bdf',
    messagingSenderId: '365750482574',
    projectId: 'send-push-e6999',
    storageBucket: 'send-push-e6999.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3uPBnA1ffqtQiDkiK-ZGASUmh9tRRguc',
    appId: '1:365750482574:web:ada4be5ab68eecc18d7bdf',
    messagingSenderId: '365750482574',
    projectId: 'send-push-e6999',
    authDomain: 'send-push-e6999.firebaseapp.com',
    storageBucket: 'send-push-e6999.firebasestorage.app',
    measurementId: 'G-NF8D9020J8',
  );
}
